using System.Collections.Generic;
using CeleTech.ShuttleExtension.ModularShuttle.UI.ShuttleControl.Shell;

namespace CeleTech.ShuttleExtension.ModularShuttle.UI.ShuttleControl.Shell.Tutorial
{
    internal sealed class ShuttleMainTutorialDefinitionBuilder
    {
        internal ShuttleTutorialDefinition Build()
        {
            List<ShuttleTutorialStep> steps = new List<ShuttleTutorialStep>();
            this.AddHeaderSteps(steps);
            this.AddBodySteps(steps);
            return new ShuttleTutorialDefinition(ShuttleControlPageId.Main, steps);
        }

        private void AddHeaderSteps(List<ShuttleTutorialStep> steps)
        {
            ShuttleTutorialStepFactory.Add(
                steps,
                null,
                "CT_Shuttle_Tutorial_Main_Guide_Title",
                "CT_Shuttle_Tutorial_Main_Guide_Body",
                ShuttleTutorialPlacement.Center,
                0f,
                null,
                ShuttleTutorialPreAction.None,
                1.6f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.HeaderStatusCards,
                "CT_Shuttle_Tutorial_Main_StatusCards_Title",
                "CT_Shuttle_Tutorial_Main_StatusCards_Body",
                ShuttleTutorialPlacement.Below,
                4f,
                null,
                ShuttleTutorialPreAction.None,
                2.2f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.HeaderLoadCargoButton,
                "CT_Shuttle_Tutorial_Main_LoadCargo_Title",
                "CT_Shuttle_Tutorial_Main_LoadCargo_Body",
                ShuttleTutorialPlacement.Below,
                4f,
                null,
                ShuttleTutorialPreAction.None,
                1.8f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.HeaderCargoUnloadButton,
                "CT_Shuttle_Tutorial_Main_TaskQueue_Title",
                "CT_Shuttle_Tutorial_Main_TaskQueue_Body",
                ShuttleTutorialPlacement.Below,
                4f,
                null,
                ShuttleTutorialPreAction.None,
                1.8f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.HeaderPageSwitchButton,
                "CT_Shuttle_Tutorial_Main_PageSwitch_Title",
                "CT_Shuttle_Tutorial_Main_PageSwitch_Body",
                ShuttleTutorialPlacement.Below,
                4f,
                null,
                ShuttleTutorialPreAction.None,
                1.8f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.HeaderLaunchButton,
                "CT_Shuttle_Tutorial_Main_Launch_Title",
                "CT_Shuttle_Tutorial_Main_Launch_Body",
                ShuttleTutorialPlacement.Below,
                4f,
                null,
                ShuttleTutorialPreAction.None,
                1.8f,
                true);
        }

        private void AddBodySteps(List<ShuttleTutorialStep> steps)
        {
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainSegmentPanel,
                "CT_Shuttle_Tutorial_Main_SegmentPanel_Title",
                "CT_Shuttle_Tutorial_Main_SegmentPanel_Body",
                ShuttleTutorialPlacement.Right,
                6f,
                null,
                ShuttleTutorialPreAction.MainResetSegmentScroll,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainRequiredSegmentCockpit,
                "CT_Shuttle_Tutorial_Main_RequiredSegmentCockpit_Title",
                "CT_Shuttle_Tutorial_Main_RequiredSegmentCockpit_Body",
                ShuttleTutorialPlacement.Right,
                4f,
                ShuttleTutorialTargetIds.MainSegmentPanel,
                ShuttleTutorialPreAction.MainResetSegmentScroll,
                2.2f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainRequiredSegmentCockpitControls,
                "CT_Shuttle_Tutorial_Main_SegmentCardControls_Title",
                "CT_Shuttle_Tutorial_Main_SegmentCardControls_Body",
                ShuttleTutorialPlacement.Right,
                3f,
                ShuttleTutorialTargetIds.MainRequiredSegmentCockpit,
                ShuttleTutorialPreAction.MainResetSegmentScroll,
                2.2f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainRequiredSegmentPower,
                "CT_Shuttle_Tutorial_Main_RequiredSegmentPower_Title",
                "CT_Shuttle_Tutorial_Main_RequiredSegmentPower_Body",
                ShuttleTutorialPlacement.Right,
                4f,
                ShuttleTutorialTargetIds.MainSegmentPanel,
                ShuttleTutorialPreAction.MainResetSegmentScroll,
                2.2f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainRequiredSegmentCargo,
                "CT_Shuttle_Tutorial_Main_RequiredSegmentCargo_Title",
                "CT_Shuttle_Tutorial_Main_RequiredSegmentCargo_Body",
                ShuttleTutorialPlacement.Right,
                4f,
                ShuttleTutorialTargetIds.MainSegmentPanel,
                ShuttleTutorialPreAction.MainResetSegmentScroll,
                2.2f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainOptionalSegments,
                "CT_Shuttle_Tutorial_Main_OptionalSegments_Title",
                "CT_Shuttle_Tutorial_Main_OptionalSegments_Body",
                ShuttleTutorialPlacement.Right,
                4f,
                ShuttleTutorialTargetIds.MainSegmentPanel,
                ShuttleTutorialPreAction.MainFocusOptionalSegment,
                2.2f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainVisualizationPanel,
                "CT_Shuttle_Tutorial_Main_Visualization_Title",
                "CT_Shuttle_Tutorial_Main_Visualization_Body",
                ShuttleTutorialPlacement.Right,
                6f,
                null,
                ShuttleTutorialPreAction.None,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainFunctionModulePanel,
                "CT_Shuttle_Tutorial_Main_FunctionModules_Title",
                "CT_Shuttle_Tutorial_Main_FunctionModules_Body",
                ShuttleTutorialPlacement.Left,
                6f,
                null,
                ShuttleTutorialPreAction.None,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainSelectedSegmentModulesPanel,
                "CT_Shuttle_Tutorial_Main_SegmentModuleRelation_Title",
                "CT_Shuttle_Tutorial_Main_SegmentModuleRelation_Body",
                ShuttleTutorialPlacement.Left,
                6f,
                null,
                ShuttleTutorialPreAction.None,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MainSelectedSegmentModulesPanel,
                "CT_Shuttle_Tutorial_Main_SelectedSegmentModules_Title",
                "CT_Shuttle_Tutorial_Main_SelectedSegmentModules_Body",
                ShuttleTutorialPlacement.Left,
                6f,
                null,
                ShuttleTutorialPreAction.None,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.InfoPanelContentList,
                "CT_Shuttle_Tutorial_Main_CurrentIssues_Title",
                "CT_Shuttle_Tutorial_Main_CurrentIssues_Body",
                ShuttleTutorialPlacement.Above,
                6f,
                ShuttleTutorialTargetIds.MainMessagePanel,
                ShuttleTutorialPreAction.MainShowCurrentIssues,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.InfoPanelLaunchChecklistTab,
                "CT_Shuttle_Tutorial_Main_LaunchChecklistTab_Title",
                "CT_Shuttle_Tutorial_Main_LaunchChecklistTab_Body",
                ShuttleTutorialPlacement.Above,
                4f,
                ShuttleTutorialTargetIds.MainMessagePanel,
                ShuttleTutorialPreAction.MainShowCurrentIssues,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.InfoPanelContentList,
                "CT_Shuttle_Tutorial_Main_LaunchChecklistList_Title",
                "CT_Shuttle_Tutorial_Main_LaunchChecklistList_Body",
                ShuttleTutorialPlacement.Above,
                6f,
                ShuttleTutorialTargetIds.MainMessagePanel,
                ShuttleTutorialPreAction.MainShowLaunchChecklist,
                2.4f);
        }
    }
}
