using System.Collections.Generic;
using CeleTech.ShuttleExtension.ModularShuttle.UI.ShuttleControl.Shell;

namespace CeleTech.ShuttleExtension.ModularShuttle.UI.ShuttleControl.Shell.Tutorial
{
    internal sealed class ShuttleMedicalTutorialDefinitionBuilder
    {
        internal ShuttleTutorialDefinition Build()
        {
            List<ShuttleTutorialStep> steps = new List<ShuttleTutorialStep>();
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalOverviewPanel,
                "CT_Shuttle_Tutorial_Medical_Overview_Title",
                "CT_Shuttle_Tutorial_Medical_Overview_Body",
                ShuttleTutorialPlacement.Auto,
                6f,
                null,
                ShuttleTutorialPreAction.None,
                2.0f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalPatientListPanel,
                "CT_Shuttle_Tutorial_Medical_PatientList_Title",
                "CT_Shuttle_Tutorial_Medical_PatientList_Body",
                ShuttleTutorialPlacement.Right,
                6f,
                ShuttleTutorialTargetIds.MedicalOverviewPanel,
                ShuttleTutorialPreAction.None,
                2.2f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalAdmissionPanel,
                "CT_Shuttle_Tutorial_Medical_Admission_Title",
                "CT_Shuttle_Tutorial_Medical_Admission_Body",
                ShuttleTutorialPlacement.Right,
                6f,
                ShuttleTutorialTargetIds.MedicalActionButtonsPanel,
                ShuttleTutorialPreAction.None,
                2.8f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalPatientDetailPanel,
                "CT_Shuttle_Tutorial_Medical_PatientDetail_Title",
                "CT_Shuttle_Tutorial_Medical_PatientDetail_Body",
                ShuttleTutorialPlacement.Left,
                6f,
                ShuttleTutorialTargetIds.MedicalOverviewPanel,
                ShuttleTutorialPreAction.None,
                2.2f);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalTreatmentPanel,
                "CT_Shuttle_Tutorial_Medical_Treatment_Title",
                "CT_Shuttle_Tutorial_Medical_Treatment_Body",
                ShuttleTutorialPlacement.Left,
                6f,
                ShuttleTutorialTargetIds.MedicalActionButtonsPanel,
                ShuttleTutorialPreAction.None,
                2.6f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalSurgeryPanel,
                "CT_Shuttle_Tutorial_Medical_Surgery_Title",
                "CT_Shuttle_Tutorial_Medical_Surgery_Body",
                ShuttleTutorialPlacement.Left,
                6f,
                ShuttleTutorialTargetIds.MedicalActionButtonsPanel,
                ShuttleTutorialPreAction.None,
                3.2f,
                true,
                "CT_Shuttle_Tutorial_Medical_SurgeryPauseWarning");
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalProcedureStatusPanel,
                "CT_Shuttle_Tutorial_Medical_ProcedureStatus_Title",
                "CT_Shuttle_Tutorial_Medical_ProcedureStatus_Body",
                ShuttleTutorialPlacement.Left,
                6f,
                ShuttleTutorialTargetIds.MedicalPatientDetailPanel,
                ShuttleTutorialPreAction.None,
                2.4f,
                true);
            ShuttleTutorialStepFactory.Add(
                steps,
                ShuttleTutorialTargetIds.MedicalMessagesPanel,
                "CT_Shuttle_Tutorial_Medical_Messages_Title",
                "CT_Shuttle_Tutorial_Medical_Messages_Body",
                ShuttleTutorialPlacement.Above,
                6f,
                ShuttleTutorialTargetIds.MedicalOverviewPanel,
                ShuttleTutorialPreAction.None,
                2.4f,
                true);
            return new ShuttleTutorialDefinition(ShuttleControlPageId.Medical, steps);
        }
    }
}
